# Generated by Django 5.1.7 on 2025-12-09 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qfs_symbol', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('analyst_name', models.CharField(blank=True, max_length=150)),
                ('price_target', models.FloatField()),
                ('current_price_at_submission', models.FloatField(blank=True, null=True)),
                ('thesis', models.TextField(blank=True, help_text='Investment thesis or notes', null=True)),
                ('tags', models.CharField(blank=True, help_text="e.g., 'Bull Case', 'Q3 Update'", max_length=100)),
                ('model_inputs', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['qfs_symbol', 'created_at'], name='valuation_h_qfs_sym_b53195_idx')],
            },
        ),
    ]
