# Generated by Django 5.1.7 on 2025-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuationsnapshot',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='valuationsnapshot',
            name='thesis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
