# Generated by Django 4.2.17 on 2025-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommetrics",
            name="html_formula",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
