# Generated by Django 5.1.7 on 2025-05-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0003_filterviews"),
    ]

    operations = [
        migrations.RemoveField(model_name="custommetrics", name="table",),
    ]
