# Generated by Django 5.1.7 on 2025-04-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradedcompanies",
            name="has_new_financials",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
