# Generated by Django 5.1.7 on 2025-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0002_alter_tradedcompanies_has_new_financials"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuation",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
