# Generated by Django 5.1.7 on 2025-04-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0003_valuation_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="EPSForecasts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("low", models.FloatField(blank=True, null=True)),
                ("avg", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                (
                    "qfs_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickfs_dj.tradedcompanies",
                        to_field="qfs_symbol",
                    ),
                ),
            ],
            options={"unique_together": {("qfs_symbol", "year")},},
        ),
    ]
