# Generated by Django 5.1.7 on 2025-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0004_epsforecasts"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheetannual",
            name="operating_assets",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Assets"
            ),
        ),
        migrations.AddField(
            model_name="balancesheetannual",
            name="operating_liabilities",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Liabilities"
            ),
        ),
    ]
