# Generated by Django 5.1.7 on 2025-05-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0005_balancesheetannual_operating_assets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheetannual",
            name="net_operating_assets",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Net Operating Assets"
            ),
        ),
    ]
