# Generated by Django 5.1.7 on 2025-05-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0006_balancesheetannual_net_operating_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyratiosannual",
            name="rnoa",
            field=models.FloatField(blank=True, null=True, verbose_name="RNOA"),
        ),
    ]
