# Generated by Django 5.1.7 on 2025-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0007_keyratiosannual_rnoa"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheetquarter",
            name="net_operating_assets",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Net Operating Assets"
            ),
        ),
        migrations.AddField(
            model_name="balancesheetquarter",
            name="operating_assets",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Assets"
            ),
        ),
        migrations.AddField(
            model_name="balancesheetquarter",
            name="operating_liabilities",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Liabilities"
            ),
        ),
    ]
