# Generated by Django 5.1.7 on 2025-05-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0008_balancesheetquarter_net_operating_assets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestbalancesheetannual",
            name="net_operating_assets",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="latestbalancesheetannual",
            name="operating_assets",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="latestbalancesheetannual",
            name="operating_liabilities",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="latestbalancesheetquarter",
            name="net_operating_assets",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="latestbalancesheetquarter",
            name="operating_assets",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="latestbalancesheetquarter",
            name="operating_liabilities",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuation",
            name="penman_equity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuation",
            name="penman_g",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuation",
            name="penman_per_share",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
