# Generated by Django 5.1.7 on 2025-05-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0009_latestbalancesheetannual_net_operating_assets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuation",
            name="penman_equity_ttm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuation",
            name="penman_g_ttm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuation",
            name="penman_per_share_ttm",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
