# Generated by Django 5.1.7 on 2025-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quickfs_dj",
            "0010_valuation_penman_equity_ttm_valuation_penman_g_ttm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="valuation",
            name="rnoa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuation",
            name="rnoa_ttm",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
