# Generated by Django 5.1.7 on 2025-05-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0011_valuation_rnoa_valuation_rnoa_ttm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epv_business", models.FloatField(blank=True, null=True)),
                ("epv_per_share", models.FloatField(blank=True, null=True)),
                ("epv_business_ttm", models.FloatField(blank=True, null=True)),
                ("epv_per_share_ttm", models.FloatField(blank=True, null=True)),
                ("penman_equity", models.FloatField(blank=True, null=True)),
                ("penman_per_share", models.FloatField(blank=True, null=True)),
                ("penman_g", models.FloatField(blank=True, null=True)),
                ("rnoa", models.FloatField(blank=True, null=True)),
                ("penman_equity_ttm", models.FloatField(blank=True, null=True)),
                ("penman_per_share_ttm", models.FloatField(blank=True, null=True)),
                ("penman_g_ttm", models.FloatField(blank=True, null=True)),
                ("rnoa_ttm", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("revenue_y", models.FloatField(blank=True, null=True)),
                ("cogs_y", models.FloatField(blank=True, null=True)),
                ("gross_profit_y", models.FloatField(blank=True, null=True)),
                ("sga_y", models.FloatField(blank=True, null=True)),
                ("rnd_y", models.FloatField(blank=True, null=True)),
                ("special_charges_y", models.FloatField(blank=True, null=True)),
                ("other_opex_y", models.FloatField(blank=True, null=True)),
                ("total_opex_y", models.FloatField(blank=True, null=True)),
                ("operating_income_y", models.FloatField(blank=True, null=True)),
                ("interest_income_y", models.FloatField(blank=True, null=True)),
                ("interest_expense_y", models.FloatField(blank=True, null=True)),
                (
                    "net_interest_income_normal_y",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "other_nonoperating_income_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("pretax_income_y", models.FloatField(blank=True, null=True)),
                ("income_tax_y", models.FloatField(blank=True, null=True)),
                ("net_income_continuing_y", models.FloatField(blank=True, null=True)),
                ("net_income_discontinued_y", models.FloatField(blank=True, null=True)),
                (
                    "income_allocated_to_minority_interest_y",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "other_income_statement_items_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("net_income_y", models.FloatField(blank=True, null=True)),
                ("preferred_dividends_y", models.FloatField(blank=True, null=True)),
                (
                    "net_income_available_to_shareholders_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("eps_basic_y", models.FloatField(blank=True, null=True)),
                ("eps_diluted_y", models.FloatField(blank=True, null=True)),
                ("shares_basic_y", models.FloatField(blank=True, null=True)),
                ("shares_diluted_y", models.FloatField(blank=True, null=True)),
                ("shares_eop_y", models.FloatField(blank=True, null=True)),
                ("shares_eop_change_y", models.FloatField(blank=True, null=True)),
                ("cash_and_equiv_y", models.FloatField(blank=True, null=True)),
                ("st_investments_y", models.FloatField(blank=True, null=True)),
                ("receivables_y", models.FloatField(blank=True, null=True)),
                ("inventories_y", models.FloatField(blank=True, null=True)),
                ("other_current_assets_y", models.FloatField(blank=True, null=True)),
                ("total_current_assets_y", models.FloatField(blank=True, null=True)),
                (
                    "equity_and_other_investments_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("ppe_gross_y", models.FloatField(blank=True, null=True)),
                (
                    "accumulated_depreciation_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("ppe_net_y", models.FloatField(blank=True, null=True)),
                ("intangible_assets_y", models.FloatField(blank=True, null=True)),
                ("goodwill_y", models.FloatField(blank=True, null=True)),
                ("other_lt_assets_y", models.FloatField(blank=True, null=True)),
                ("total_assets_y", models.FloatField(blank=True, null=True)),
                ("accounts_payable_y", models.FloatField(blank=True, null=True)),
                ("tax_payable_y", models.FloatField(blank=True, null=True)),
                (
                    "current_accrued_liabilities_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("st_debt_y", models.FloatField(blank=True, null=True)),
                (
                    "current_deferred_revenue_y",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "current_deferred_tax_liability_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("current_capital_leases_y", models.FloatField(blank=True, null=True)),
                (
                    "other_current_liabilities_y",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "total_current_liabilities_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("lt_debt_y", models.FloatField(blank=True, null=True)),
                (
                    "noncurrent_capital_leases_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("pension_liabilities_y", models.FloatField(blank=True, null=True)),
                (
                    "noncurrent_deferred_revenue_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("other_lt_liabilities_y", models.FloatField(blank=True, null=True)),
                ("total_liabilities_y", models.FloatField(blank=True, null=True)),
                ("common_stock_y", models.FloatField(blank=True, null=True)),
                ("preferred_stock_y", models.FloatField(blank=True, null=True)),
                ("retained_earnings_y", models.FloatField(blank=True, null=True)),
                ("aoci_y", models.FloatField(blank=True, null=True)),
                ("apic_y", models.FloatField(blank=True, null=True)),
                ("treasury_stock_y", models.FloatField(blank=True, null=True)),
                ("other_equity_y", models.FloatField(blank=True, null=True)),
                (
                    "minority_interest_liability_y",
                    models.FloatField(blank=True, null=True),
                ),
                ("total_equity_y", models.FloatField(blank=True, null=True)),
                (
                    "total_liabilities_and_equity_y",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "qfs_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickfs_dj.tradedcompanies",
                        to_field="qfs_symbol",
                    ),
                ),
            ],
        ),
    ]
