# Generated by Django 5.1.7 on 2025-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0012_screenerdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenerdata",
            name="accounts_payable_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="accumulated_depreciation_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="aoci_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="apic_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="assets_to_equity_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="assets_to_equity_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Assets to Equity"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="book_value_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="book_value_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Book Value per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="book_value_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="book_value_y",
            field=models.FloatField(blank=True, null=True, verbose_name="Book Value"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="capex_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="capex_growth_y",
            field=models.FloatField(blank=True, null=True, verbose_name="Capex Growth"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="capex_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="capex_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Capital Expenditures (Capex)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cash_and_equiv_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cash_and_equiv_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Cash and Equivalents Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cash_and_equiv_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cf_cff_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Cash from Financing (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cf_cfi_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Cash from Investing (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cf_cfo_cagr_10_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cf_cfo_cagr_10_y",
            field=models.FloatField(blank=True, null=True, verbose_name="CFO CAGR 10Y"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cf_cfo_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Cash from Operations (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_common_stock_issued_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Common Stock Issued (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_common_stock_net_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Common Stock Net (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_common_stock_repurchased_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Common Stock Repurchased (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_debt_issued_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Debt Issued (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_debt_net_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Debt Net (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_debt_repaid_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Debt Repaid (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_dividend_paid_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Dividend Paid (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_other_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Other Financing Cash Flows (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_pfd_issued_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Preferred Stocks Issued (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_pfd_net_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Preferred Stocks Net (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cff_pfd_repurchased_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Preferred Stocks Repurchased (CFF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_acquisitions_net_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Acquisitions Net (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_acquisitions_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Acquisitions (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_divestitures_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Divestitures (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_intangibles_net_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Intangibles Net (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_investment_net_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Investments Net (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_investment_purchases_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Investment Purchases (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_investment_sales_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Investment Sales (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_other_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Other Investing Cash Flows (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_ppe_net_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="PP&E Net (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_ppe_purchases_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="PP&E Purchases (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfi_ppe_sales_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="PP&E Sales (CFI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_change_in_working_capital_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Change in Working Capital (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_da_y",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Depreciation and Amortization (CFO)",
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_deferred_tax_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Deferred Tax (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Cash Flow Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_inventory_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Inventory (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_net_income_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Net Income (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_other_noncash_items_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Other Non-Cash items (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_other_working_capital_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Other Working Capital (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_prepaid_expenses_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Prepaid Expenses (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_receivables_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Accounts Receivables (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="cfo_stock_comp_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Stock Compensation (CFO)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="common_stock_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="current_accrued_liabilities_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="current_capital_leases_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="current_deferred_revenue_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="current_deferred_tax_liability_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="current_ratio_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="current_ratio_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Current Ratio"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="debt_to_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="debt_to_assets_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Debt to Assets"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="debt_to_equity_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="debt_to_equity_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Debt to Equity"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="dividends_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="dividends_y",
            field=models.FloatField(blank=True, null=True, verbose_name="Dividends"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="earning_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="earning_assets_to_equity_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="earning_assets_to_equity_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Earning Assets to Equity"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="earning_assets_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Earnings Assets"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="EBITDA Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_margin_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="EBITDA Margin"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="EBITDA per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ebitda_y",
            field=models.FloatField(blank=True, null=True, verbose_name="EBITDA"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_book_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_book_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Enterprise Value to Book (EV/B)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_earnings_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_earnings_y",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Enterprise Value to Earnings (EV/E)",
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_fcf_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_fcf_y",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Enterprise Value to Free Cash Flow (EV/FCF)",
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_pretax_income_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_pretax_income_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Enterprise Value to Pretax Income"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_sales_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_sales_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Enterprise Value to Sales (EV/S)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_tangible_book_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_to_tangible_book_y",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Enterprise Value to Tangible Book (EV/TB)",
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="enterprise_value_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Enterprise Value (EV)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="eps_diluted_cagr_10_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="eps_diluted_cagr_10_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="EPS diluted CAGR 10Y"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="eps_diluted_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="eps_diluted_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="EPS diluted Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="equity_and_other_investments_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="equity_to_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="equity_to_assets_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Equity to Assets"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_cagr_10_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_cagr_10_y",
            field=models.FloatField(blank=True, null=True, verbose_name="FCF CAGR 10Y"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Free Cash Flow Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_margin_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Free Cash Flow Margin"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="FCF per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="fcf_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Free Cash Flow (FCF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="goodwill_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="gross_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="gross_margin_y",
            field=models.FloatField(blank=True, null=True, verbose_name="Gross Margin"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="gross_profit_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="gross_profit_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gross Profit Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="income_tax_rate_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="income_tax_rate_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Income Tax Rate"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="intangible_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="inventories_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="loan_loss_reserve_to_loans_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="loan_loss_reserve_to_loans_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Loan Loss Reserve to Loans"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="loans_to_deposits_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="loans_to_deposits_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Loans to Deposits"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="lt_debt_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="market_cap_q",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="market_cap_y",
            field=models.FloatField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Market Capitalization",
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_debt_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_debt_y",
            field=models.FloatField(blank=True, null=True, verbose_name="Net Debt"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_income_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_income_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Net Income Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_income_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_income_margin_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Net Income Margin"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_interest_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="net_interest_margin_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Net Interest Margin"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="noncurrent_capital_leases_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="noncurrent_deferred_revenue_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="operating_income_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="operating_income_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Income Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="operating_income_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="operating_income_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Income per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="operating_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="operating_margin_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Operating Margin"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="other_current_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="other_current_liabilities_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="other_equity_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="other_lt_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="other_lt_liabilities_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="payout_ratio_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="payout_ratio_y",
            field=models.FloatField(blank=True, null=True, verbose_name="Payout Ratio"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="pension_liabilities_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="period_end_price_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="period_end_price_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Period End Price"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="policy_revenue_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="policy_revenue_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Policy Revenue"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ppe_gross_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ppe_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ppe_growth_y",
            field=models.FloatField(blank=True, null=True, verbose_name="PP&E Growth"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ppe_net_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="preferred_stock_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="premiums_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="premiums_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Premiums per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="pretax_income_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="pretax_income_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pretax Income Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="pretax_income_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="pretax_income_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pretax Income per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="pretax_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="pretax_margin_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pretax Margin"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_book_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_book_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Price-to-Book (P/B)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_earnings_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_earnings_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Price-to-Earnings (P/E)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_fcf_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_fcf_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Price to Free Cash Flow (P/FCF)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_pretax_income_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_pretax_income_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Price to Pretax Income"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_sales_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_sales_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Price-to-Sales (P/S)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_tangible_book_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="price_to_tangible_book_y",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Price-to-Tangible-Book-Value (PTBV)",
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="receivables_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="retained_earnings_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="revenue_cagr_10_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="revenue_cagr_10_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Revenue CAGR 10Y"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="revenue_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="revenue_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Revenue Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="revenue_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="revenue_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Revenue per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="rnoa_y",
            field=models.FloatField(blank=True, null=True, verbose_name="RNOA"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roa_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roa_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Return on Assets (ROA)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roce_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roce_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Return on Capital Employed"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roe_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roe_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Return on Equity (ROE)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roi_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roi_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Return on Investment (ROI)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roic_legacy_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roic_legacy_y",
            field=models.FloatField(blank=True, null=True, verbose_name="ROIC legacy"),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roic_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="roic_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Return on Invested Capital (ROIC)"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="rotce_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="rotce_y",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Return on Tangible Capital Employed",
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="shares_diluted_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="shares_diluted_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Shares Diluted Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="shares_eop_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="shares_eop_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Shares EOP Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="st_debt_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="st_investments_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="tangible_book_per_share_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="tangible_book_per_share_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Tangible Book per Share"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="tangible_book_value_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="tangible_book_value_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Tangible Book Value"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="tax_payable_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_assets_cagr_10_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_assets_cagr_10_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Total Assets CAGR 10Y"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_assets_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_assets_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Total Assets Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_current_assets_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_current_liabilities_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_equity_cagr_10_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_equity_cagr_10_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Total Equity CAGR 10Y"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_equity_growth_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_equity_growth_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Total Equity Growth"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="total_liabilities_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="treasury_stock_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="underwriting_margin_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="underwriting_margin_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Underwriting Margin"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="underwriting_profit_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="underwriting_profit_y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Underwriting Profit"
            ),
        ),
        migrations.AddConstraint(
            model_name="screenerdata",
            constraint=models.UniqueConstraint(
                fields=("qfs_symbol",), name="unique_qfs_symbol"
            ),
        ),
    ]
