# Generated by Django 5.1.7 on 2025-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0013_screenerdata_accounts_payable_q_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenerdata",
            name="exchange",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Exchange"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="industry",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Industry"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="screenerdata",
            name="ticker",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
