# Generated by Django 5.1.7 on 2025-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0014_screenerdata_exchange_screenerdata_industry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenerdata",
            name="last_close_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Last close price"
            ),
        ),
    ]
