# Generated by Django 5.1.7 on 2025-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickfs_dj", "0015_screenerdata_last_close_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomestatementannual",
            name="shares_diluted",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Shares (Diluted)"
            ),
        ),
    ]
