# Generated by Django 5.1.7 on 2025-12-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Key assumptions or thesis', null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='price_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
