# Generated by Django 5.1.7 on 2025-12-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlistitem_notes_watchlistitem_price_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='valuation_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
