# Generated by Django 5.1.7 on 2025-12-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_watchlistitem_valuation_inputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='price_target',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='valuation_date',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='valuation_inputs',
        ),
        migrations.CreateModel(
            name='StockValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_target', models.FloatField(blank=True, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('valuation_inputs', models.JSONField(blank=True, null=True)),
                ('watchlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='watchlist.watchlistitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
