name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "value-investing-backend/valueinvesting/**"

jobs:
  backend-deploy:
    uses: ./.github/workflows/deploy-ecs.yml
    with:
      ecr_image: ${{ vars.ECR_BACKEND_IMAGE }}
      ecs_service: ${{ vars.ECS_BACKEND_SERVICE }}
      context_path: ./value-investing-backend/valueinvesting/
